import Head from 'next/head';
import { getSession, useSession } from 'next-auth/react';
import Login from '../components/auth/login';

import {
  getActionMovie,
  getComedyMovie,
  getDocumentariesMovie,
  getHorrorMovie,
  getMoviePosters,
  getRomanceMovie,
  getTopRate,
  getTrendig,
} from '../utils/requests/fetchers';

import LandingPage from '../components/videos';

//=====================================================
export default function Home({
  posters,
  trends,
  actionMovies,
  topRated,
  comedyMovies,
  horrorMovies,
  romanceMovie,
  documentaries,
}) {
  const { data: session } = useSession();

  // if (!session) return <Login />;

  return (
    <>
      <Head>
        <title>clone-netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>

      <main className='relative bg-gradient-to-b from-gray-900/10 to-[#010511] '>
        <LandingPage
          posters={posters}
          trends={trends}
          topRated={topRated}
          actionMovies={actionMovies}
          comedyMovies={comedyMovies}
          horrorMovies={horrorMovies}
          romanceMovie={romanceMovie}
          documentaries={documentaries}
        />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  const posters = await getMoviePosters();
  const trends = await getTrendig();
  const topRated = await getTopRate();
  const actionMovies = await getActionMovie();
  const comedyMovies = await getComedyMovie();
  const horrorMovies = await getHorrorMovie();
  const romanceMovie = await getRomanceMovie();
  const documentaries = await getDocumentariesMovie();

  return {
    props: {
      session,
      posters,
      trends,
      actionMovies,
      topRated,
      comedyMovies,
      horrorMovies,
      romanceMovie,
      documentaries,
    },
  };
}
