import Head from 'next/head';
import { getSession, useSession } from 'next-auth/react';
import Login from '../components/auth/login';
import Navbar from '../components/layer/navbar';
//=====================================================
export default function Home() {
  const { data: session } = useSession();

  // if (!session) return <Login />;

  return (
    <>
      <Head>
        <title>clone-netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>

      <main>
        <Navbar />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
